### ISSUE TITLE
Using InvenioConfigEnvironment breaks celery worker logging

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio-config#21]
Both INSPIRE and Zenodo use the following code (https://github.com/zenodo/zenodo/blob/master/zenodo/celery.py#L42-L44) to allow Sentry logging from inside workers.

If the overlay uses environment variables for configuration, the following line will be executed https://github.com/inveniosoftware/invenio-config/blob/master/invenio_config/env.py#L64 which will then make logging not work.

I have narrowed down the problem to that specific line and commenting it out makes things work, but I don't know what is the correct way of fixing that problem.

CC @lnielsen

**Comment by jirikuncar** [comment]
@jmartinm is it possible to create a test case for it?

**Comment by jmartinm** [comment]
Test is complex seems it involves a worker running in non-eager mode, a mocked Sentry instance and making sure that a call to the worker `logger` would send a request to the Sentry instance.

By reading this issue https://github.com/celery/celery/issues/2509 , the solution to the problem is this PR (https://github.com/inveniosoftware/flask-celeryext/pull/26) which also avoid having [these lines](https://github.com/zenodo/zenodo/blob/master/zenodo/celery.py#L42-L44)
