### ISSUE TITLE
config: pass environment variables to FLASK

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-config#37]
Right now what is supported, is to pass environment variables that are prefixed in order to be handled inside the flask application. The problem is that you cannot pass flask variables through environment because of the prefixing. It would be nice to create a specific prefix to indicate that these variables are meant to configure flask and trim the prefix beforehand.

**Comment by lnielsen** [comment]
Do you have an example which fails? Then we can fix it during the sprint.

**Comment by zzacharo** [comment]
An example is the `SQLALCHMEY_DATABASE_URI` which I want to pass from an environmental variable in openshift.The reason is that this uri contains the password of the database and in openshift it is not possible to create a secret variable for a config variable.

**Comment by lnielsen** [comment]
This should already be working. See e.g.:
```
https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/docker-services.yml#L19-L23
```

Note also that the prefix for environment variables is [stripped](https://github.com/inveniosoftware/invenio-config/blob/master/invenio_config/env.py#L37). E.g. env variable ``INVENIO_ SQLALCHMEY_DATABASE_URI`` will set the config variable ``SQLALCHMEY_DATABASE_URI``

I'm closing for now as I'm quite sure it works, however, if not then please just reopen.
